name: Frontend

on:
  workflow_call:

jobs:
  test:
    env:
      CI: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM build
        run: |
          cd taxonium_website
          npm install -g yarn
          yarn install
          yarn build
          cd build
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: taxonium_website
          path: taxonium_website/build
          retention-days: 5
